export const projectsData = [
  {
    id: 1,
    title: "myFlixAPI",
    description:
      "RESTful API using Node.js and Express, that interacts with a non-relational database (MongoDB). The API can be accessed via commonly used HTTP methods like GET or POST. To retrieve data from and store data in the database, CRUD methods are used. The API provides movie information in JSON format.",
    gitHubLink: "https://github.com/cezarszl/myFlixAPI",
    demo: "https://cezarszlmyflix-0212aa467a8d.herokuapp.com/",
    technologies: "Node.js, MongoDB, Express",
    imagePath1: "/images/projects/myflixapi1.png",
    imagePath2: "/images/projects/myflixapi2.png",
  },
  {
    id: 2,
    title: "myFlixClient (React)",
    description:
      "React-based client-side application designed for movie enthusiasts to explore and save their favorite films. Leveraging a REST API and database, it offers a seamless user experience with features like browsing movies, user authentication, profile management.",
    gitHubLink: "https://github.com/cezarszl/myFlix-client",
    demo: "https://cezarszl.netlify.app/",
    technologies: "React, Redux, Bootstrap",
    imagePath1: "/images/projects/myflixclient2.png",
    imagePath2: "/images/projects/myflixclient2.png",
  },
  {
    id: 3,
    title: "myFlixClient (Angular)",
    description:
      "Angular-based client-side application developed to complement its existing server-side REST API and database. Through this project, I demonstrated proficiency in Angular, user authentication, and responsive design using Angular Material. The project also highlights my skills in documentation and collaboration, crucial for modern development environments.",
    gitHubLink: "https://github.com/cezarszl/myFlix-Angular-client",
    demo: "https://portfolio-47t12ahkx-cezars-projects-4901e2db.vercel.app/",
    technologies: "Angular, Typescript, AngularMaterial, TypDoc",
    imagePath1: "/images/projects/myflixangular1.png",
    imagePath2: "/images/projects/myflixangular2.png",
  },
  {
    id: 4,
    title: "Meet App",
    description:
      "A cutting-edge progressive web application (PWA) crafted with React and employing serverless architecture. Developed through a test-driven approach, it seamlessly integrates the Google Calendar API for fetching upcoming events. With features like city-based event filtering, offline functionality, and interactive data visualization, this app offers users a dynamic and immersive experience.",
    gitHubLink: "https://github.com/cezarszl/meet",
    demo: "https://cezarszl.github.io/meet/",
    technologies: "React, AWS Lambda, OAuth, Google Calendar API",
    imagePath1: "/images/projects/meet1.png",
    imagePath2: "/images/projects/meet2.png",
  },
  {
    id: 5,
    title: "Chat app",
    description:
      'Mobile chat application built with React Native and Expo, offering seamless communication for users across Android and iOS devices. Leveraging Google Firestore Database and Firebase authentication, this app enables users to exchange messages, share images, and send location data. With features like offline message reading and compatibility with screen readers, "Chatify" prioritizes accessibility and user experience.',
    gitHubLink: "https://github.com/cezarszl/chat-app",
    demo: "https://github.com/cezarszl/chat-app",
    technologies: "React Native, Expo, Google Fiebase",
    imagePath1: "/images/projects/chatapp1.jpeg",
    imagePath2: "/images/projects/chatapp2.jpeg",
  },
  {
    id: 6,
    title: "PokeDex",
    description:
      "A dynamic web application showcasing expertise in HTML, CSS, and JavaScript. Utilizing an external API, it presents a user-friendly interface where users can explore a list of items, such as Pokémon, with detailed information available on demand. With clean code, CSS styling, and seamless functionality across browsers.",
    gitHubLink: "https://github.com/cezarszl/Pokedex-Simple-JS-App",
    demo: "https://cezarszl.github.io/Pokedex-Simple-JS-App/",
    technologies: "HTML, CSS, Vanilla JS, Bootstrap",
    imagePath1: "/images/projects/pokedex1.png",
    imagePath2: "/images/projects/pokedex2.png",
  },
];

export const ProjectsData = [
  {
    id: 1,
    title: "MovieScope Client (React)",
    description: "MovieScope is an app built using ReactJS, leveraging previously designed server-side code (including a REST API and database). Users can register an account, log in, and access information on a variety of movies. Additionally, the app allows users to update their personal data and create a list of favorite movies.",
    cardImage: "/projects/MovieScope.png",
    technologies: "React, Redux, Bootstrap",
    gitHubLink: "https://github.com/cezarszl/MovieScope-client",
    demoLink: "https://cezarszl.netlify.app/",
    imagePath1: "/projects/project_details/myflixclient1.png",
    imagePath2: "/projects/project_details/myflixclient2.png",

  },
  {
    id: 2,
    title: "Meet App",
    description: "Meet is a versatile events app that allows users to filter, explore, and visualize events effortlessly. Whether you're looking for local meetups or exploring events in different cities, Meet has you covered.",
    cardImage: "/projects/MeetApp.png",
    technologies: "React, AWS Lambda, OAuth, Google Calendar API",
    gitHubLink: "https://github.com/cezarszl/Meet-App",
    demoLink: "https://cezarszl.github.io/meet/",
    imagePath1: "/projects/project_details/meet1.png",
    imagePath2: "/projects/project_details/meet2.png",
  },
  {
    id: 3,
    title: "Chat App",
    description: "The Chat App is a mobile application built with React Native and Expo, providing a platform for users to engage in conversations by sending messages, images, and sharing their location. It is designed to be accessible and functional both online and offline.",
    cardImage: "/projects/Chatapp.jpeg",
    technologies: "React Native, Expo, Google Firebase",
    gitHubLink: "https://github.com/cezarszl/chatapp",
    demoLink: "",
    imagePath1: "/projects/project_details/chatapp1.png",
    imagePath2: "/projects/project_details/chatapp2.png",
  },
  {
    id: 4,
    title: "MovieScope API",
    description: "MovieScope API is a Node.js application that provides backend services for the MovieScope client. It enables operations such as user authentication, movie browsing by genre or director, and managing favorite movies lists.",
    cardImage: "/projects/MovieScopeAPI.png",
    technologies: "Node.js, MongoDB, Express",
    gitHubLink: "https://github.com/cezarszl/MovieScope-API",
    demoLink: "https://cezarszlmyflix-0212aa467a8d.herokuapp.com/",
    imagePath1: "/projects/project_details/moviescopeapi1.png",
    imagePath2: "/projects/project_details/moviescopeapi2.png",
  },
  {
    id: 5,
    title: "Pokedex",
    description: "This is a small web application that displays data from the Pokémon universe. Users can view details about different Pokémon through a simple interface that utilizes HTML, CSS, and JavaScript.",
    cardImage: "/projects/Pokedex.png",
    technologies: "jQuery, Bootsrap, Vanilla JS",
    gitHubLink: "https://github.com/cezarszl/Pokedex-Simple-JS-App",
    demoLink: "https://cezarszl.github.io/Pokedex-Simple-JS-App/",
    imagePath1: "/projects/project_details/pokedex1.png",
    imagePath2: "/projects/project_details/pokedex2.png",
  },
  {
    id: 6,
    title: "MovieScope Client (Angular)",
    description: "MovieScope is an Angular-based application that serves as a movie database, allowing users to explore detailed information about movies, directors, and genres. Users can register to create profiles and save their favorite movies.",
    cardImage: "/projects/MovieScope_Angular.png",
    technologies: "Angular, Angular Material, Node.js, TypeScript",
    gitHubLink: "https://github.com/cezarszl/MovieScope-client-Angular",
    demoLink: "https://cezarszl.github.io/MovieScope-client-Angular/",
    imagePath1: "/projects/project_details/myflixangular1.png",
    imagePath2: "/projects/project_details/myflixangular2.png",
  },
];